<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">

<?php
	
	require_once("../DataAdapter.php");

	$pptta = new PingPongTermTableAdapater();
		
	if($_POST['name'] != "")
	{
		$pptta = new PingPongTermTableAdapater();
		
		$pptta->InsertTerm($_POST['name'], $_POST['definition'], $_POST['category']);
		
	}
?>

<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>Add a Term</title>
<link rel="stylesheet" type="text/css" href="view.css" media="all">
<script type="text/javascript" src="view.js"></script>

</head>
<body id="main_body" >
	
	<img id="top" src="top.png" alt="">
	<div id="form_container">
	
		<h1><a>Add a Term</a></h1>
		<form id="formAddTerm" class="appnitro"  method="post" action="AddTerm.php">
					<div class="form_description">
			<h2>Add a Term</h2>
			<p>Add a ping pong term and definition here.</p>
		</div>						
			<ul >
			
					<li id="li_3" >
		<label class="description" for="category">Category
 </label>
		<div>
		<select class="element select medium" id="category" name="category"> 
			<?php
			
				// Populate categories
				$catsResult = $pptta->GetCategories();
				
				$iterator = 0;
				foreach($catsResult as $cat)
				{
					$selected = "";
					if($iterator++ == 0)
						$selected = 'selected = "selected"';
					echo('<option value="' . $cat['categoryId'] . '" ' . $selected . ' >' . $cat['categoryName'] . '</option>');
				}
			?>


		</select>
		</div> 
		</li>		<li id="li_1" >
		<label class="description" for="name">Name </label>
		<div>
			<input id="name" name="name" class="element text medium" type="text" maxlength="255" value=""/> 
		</div> 
		</li>		<li id="li_2" >
		<label class="description" for="definition">Definition </label>
		<div>
			<textarea id="definition" name="definition" class="element textarea medium"></textarea> 
		</div> 
		</li>
			
					<li class="buttons">
			    <input type="hidden" name="form_id" value="291701" />
			    
				<input id="saveForm" class="button_text" type="submit" name="submit" value="Submit" />
		</li>
			</ul>
		</form>	
		<div id="footer">
			Generated by <a href="http://www.phpform.org">pForm</a>
		</div>
	</div>
	<img id="bottom" src="bottom.png" alt="">
	</body>
</html>